### ISSUE TITLE
Tuning Reports

### ISSUE THREAD

**Issue by lw0** [hyrise/hyrise#719] opened 2018-02-20 11:41 UTC
Resulting from the discussion about logging #714, there seems to be a separate need for a structured, parseable representation of the decisions available and taken during a tuning process, as implemented in #715.

We (+@adi64 +@AtiX) would hereby like to start a new discussion regarding the format and level of detail that should be adopted for Tuning Reports.

**Comment by adi64** [comment] 2018-02-20 12:25
Probably a (partial?) duplicate of #683

**Closed** 2018-02-27 11:09 UTC
