### ISSUE TITLE
Caching unencoded binary tables for TPC-H is broken

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2212] opened 2020-09-11 07:40 UTC
Steps to reproduce:

1. Delete tpch_cached_tables folder
2. Run `./hyriseBenchmarkTPCH -e Unencoded`
3. Run it again

```
terminate called after throwing an instance of 'std::logic_error'
  what():  src/lib/import_export/binary/binary_parser.cpp:166 Invalid EncodingType
Aborted (core dumped)
```

**Comment by mweisgut** [comment] 2020-09-15 12:18
duplicate of #2158

**Closed by mweisgut** 2020-09-15 12:18 UTC
Labels: Bug
