### ISSUE TITLE
Multiple COUNT(*) in subqueries have same output

### ISSUE THREAD

**Issue by janetzki** [hyrise/hyrise#1822] opened 2019-09-03 09:22 UTC
The query
```sql
SELECT *
FROM
  (SELECT COUNT(*) a
  FROM store_sales) s1,
  (SELECT COUNT(*) b
  FROM inventory) s2;
```
returns the value for the column a also for the column b. This might be an issue with the `SQLTranslator` and the `SQLIdentifierResolver`, which assume that both `COUNT(*)` reference the same expression.
This bug is the reason why TPC-DS query 88 has a wrong output.

**Comment by mweisgut** [comment] 2019-09-04 07:48
duplicate of #1814
related to #1768

**Comment by mrks** [comment] 2019-09-14 18:29
I talked to mrzzzrm yesterday. We should make sure that the fix for this also covers `SELECT COUNT(*) FROM t1, t2 [...]`, where we do not have a single table that the "fake" column reference can point to. It probably doesn't even matter which of the two tables we pick, but this case should be tested.

**Closed** 2019-10-29 20:11 UTC
Labels: Bug
