### ISSUE TITLE
ClangDebugShuffle crashes

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#1739] opened 2019-07-03 12:06 UTC
The commit 383b8ed crashed in the CI during the `clangDebugRunShuffled` phase with the following error:
```
[ RUN      ] SQLPipelineStatementTest.GetResultTable
[       OK ] SQLPipelineStatementTest.GetResultTable (2 ms)
[ RUN      ] SQLPipelineStatementTest.GetQueryPlan
[       OK ] SQLPipelineStatementTest.GetQueryPlan (5 ms)
[----------] 43 tests from SQLPipelineStatementTest (1075 ms total)

[----------] 284 tests from SQLiteTestRunnerUnencoded/SQLiteTestRunner
[ RUN      ] SQLiteTestRunnerUnencoded/SQLiteTestRunner.CompareToSQLite/123
Segmentation fault (core dumped)
script returned exit code 139
```

The random seed was 79172 .

**Comment by mrks** [comment] 2019-08-09 17:32
Can't reproduce it with that exact commit and seed. As I have not seen this on any other branch either, I'll close this for now.

**Closed by mrks** 2019-08-09 17:32 UTC
Labels: DevOps
