### ISSUE TITLE
Huge memory usage increase?

### ISSUE THREAD

**Issue by mflueggen** [hyrise/hyrise#2102] opened 2020-04-24 10:19 UTC
I noticed that the memory consumption of Hyrise’s TPC-H benchmark may have increased drastically. When executing
`./hyriseBenchmarkTPCH -q 2 -s 0.1 `
from commit 8851c50467ad8d1bc792434fc55b2c0066dd48a6 (Thu Jan 23 14:12:15 2020 +010) `htop` shows ~3.4 GB of virtual memory and a resident set size of ~580 MB.

When executing the benchmark with the current master the virtual memory increases to ~24.9 GB and the resident set size increases to ~2 GB. Jemalloc reports stats.allocated = 21'800'995'904 after having executed query 2 of the TPC-H benchmark.

**Comment by mrks** [comment] 2020-04-24 10:52
I'll have a look.

Note to myself: #749? No ValueSegments should exist after `AbstractTableGenerator::generate_and_store`. Check allocations with instruments.

**Comment by mrks** [comment] 2020-04-24 12:10
Are you using cached binary tables? The log should tell you.

```
Markus.Dreseler@nemea:~/hyrise2/build-release$ rm -rf tpch_cached_tables/sf-0.100000/
Markus.Dreseler@nemea:~/hyrise2/build-release$ /usr/bin/time -v ./hyriseBenchmarkTPCH -s .1 -r 0 2>&1 | grep -E 'Command|Maximum resident'
	Command being timed: "./hyriseBenchmarkTPCH -s .1 -r 0"
	Maximum resident set size (kbytes): 1111268
Markus.Dreseler@nemea:~/hyrise2/build-release$ /usr/bin/time -v ./hyriseBenchmarkTPCH -s .1 -r 0 2>&1 | grep -E 'Command|Maximum resident'
	Command being timed: "./hyriseBenchmarkTPCH -s .1 -r 0"
	Maximum resident set size (kbytes): 249592
```

This was introduced for #749. Mutable chunks are now initialized with MAX_CHUNK_SIZE rows. This adds a temporary (!) overhead of `# columns * MAX_CHUNK_SIZE * avg_sizeof(ColumnDataType)` (and a bit more for MVCC).

**Comment by mflueggen** [comment] 2020-04-24 12:21
Yes. I am using cached tables.

**Comment by mrks** [comment] 2020-04-24 12:22
Weird. Do you have any configuration that differs from Ubuntu+gcc+release+master as used above? As you can see, I can't reproduce your 2 GB RSS.

Just double checked this in the ubuntu/20.04 image.

**Comment by mflueggen** [comment] 2020-04-24 12:25
How much virtual memory is requested on your system?

**Comment by mflueggen** [comment] 2020-04-24 12:38
Are you executing query 2?
When I execute `/usr/bin/time -v ./hyriseBenchmarkTPCH -s .1 -q 2`:
Maximum resident set size (kbytes): 2199300

When I execute `/usr/bin/time -v ./hyriseBenchmarkTPCH -s .1 -r 0 2`:
Maximum resident set size (kbytes): 253380 (This is just like your value).

**Comment by mrks** [comment] 2020-04-24 13:02
Aaah, this is actually a thing in query 2. My fault for thinking it was in the data generation and adding `-r 0`.

```
Markus.Dreseler@nemea:~/hyrise2/build-release$ /usr/bin/time -v ./hyriseBenchmarkTPCH -s .1 -q 2 -t 10 2>&1 | grep 'Maximum resident'
	Maximum resident set size (kbytes): 2255788
```


This looks interesting:

```
--------------------------------------------------------------------------------
  n        time(i)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
 25  7,579,995,392      838,991,744      825,758,079    13,233,665            0
98.42% (825,758,079B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->74.36% (623,893,200B) 0x2192A3: std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::container::pmr::polymorphic_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> > > >::reserve(unsigned long) (in /hyrise/build-release/hyriseBenchmarkTPCH)
| ->74.36% (623,893,200B) 0x157C361C: (anonymous namespace)::materialize_output_table(std::shared_ptr<opossum::Table const> const&, opossum::RowIDPosList const&, unsigned int) (in /hyrise/build-release/lib/libhyrise_impl.so)
|   ->74.36% (623,893,200B) 0x157C5AF6: opossum::Sort::_on_execute() (in /hyrise/build-release/lib/libhyrise_impl.so)
```

**Comment by mrks** [comment] 2020-04-24 13:03
Please have a look if this fixes it:

```diff
diff --git a/src/lib/operators/sort.cpp b/src/lib/operators/sort.cpp
index 1b87294fa..2186632fc 100644
--- a/src/lib/operators/sort.cpp
+++ b/src/lib/operators/sort.cpp
@@ -41,8 +41,9 @@ std::shared_ptr<Table> materialize_output_table(const std::shared_ptr<const Tabl
       auto value_segment_value_vector = pmr_vector<ColumnDataType>();
       auto value_segment_null_vector = pmr_vector<bool>();

-      value_segment_value_vector.reserve(output_chunk_size);
-      value_segment_null_vector.reserve(output_chunk_size);
+      const auto next_chunk_size = std::min(static_cast<size_t>(output_chunk_size), row_count);
+      value_segment_value_vector.reserve(next_chunk_size);
+      value_segment_null_vector.reserve(next_chunk_size);

       auto accessor_by_chunk_id =
           std::vector<std::unique_ptr<AbstractSegmentAccessor<ColumnDataType>>>(unsorted_table->chunk_count());
@@ -51,7 +52,7 @@ std::shared_ptr<Table> materialize_output_table(const std::shared_ptr<const Tabl
         accessor_by_chunk_id[input_chunk_id] = create_segment_accessor<ColumnDataType>(base_segment);
       }

-      for (auto row_index = 0u; row_index < row_count; ++row_index) {
+      for (auto row_index = size_t{0}; row_index < row_count; ++row_index) {
         const auto [chunk_id, chunk_offset] = pos_list[row_index];

         auto& accessor = accessor_by_chunk_id[chunk_id];
@@ -71,8 +72,9 @@ std::shared_ptr<Table> materialize_output_table(const std::shared_ptr<const Tabl
           value_segment_value_vector = pmr_vector<ColumnDataType>();
           value_segment_null_vector = pmr_vector<bool>();

-          value_segment_value_vector.reserve(output_chunk_size);
-          value_segment_null_vector.reserve(output_chunk_size);
+          const auto next_chunk_size = std::min(static_cast<size_t>(output_chunk_size), row_count - row_index);
+          value_segment_value_vector.reserve(next_chunk_size);
+          value_segment_null_vector.reserve(next_chunk_size);

           ++chunk_it;
         }
```

**Comment by mrks** [comment] 2020-04-24 13:07
If you haven't used patch files before: Go to the repo root, run `git apply`, paste the diff, press `ctrl+d`, done.

**Comment by mrks** [comment] 2020-04-24 13:10
At least massif says that this improved the memory consumption significantly. It's especially weird that the memory was never released:

Old:
```
    GB
14.38^                                                                       #
     |                                                                    @@@#
     |                                                                 @@@@@@#
     |                                                             @@@@@@@@@@#
     |                                                          @@@@@@@@@@@@@#
     |                                                        @:@@@@@@@@@@@@@#
     |                                                     ::@@:@@@@@@@@@@@@@#
     |                                                  @@@::@@:@@@@@@@@@@@@@#
     |                                              @@@@@ @::@@:@@@@@@@@@@@@@#
     |                                           @@@@@@@@ @::@@:@@@@@@@@@@@@@#
     |                                        @:@@@ @@@@@ @::@@:@@@@@@@@@@@@@#
     |                                     @@:@:@@@ @@@@@ @::@@:@@@@@@@@@@@@@#
     |                                   @@@@:@:@@@ @@@@@ @::@@:@@@@@@@@@@@@@#
     |                               @@@@@@@@:@:@@@ @@@@@ @::@@:@@@@@@@@@@@@@#
     |                            @@@@@@ @@@@:@:@@@ @@@@@ @::@@:@@@@@@@@@@@@@#
     |                          @@@@@@@@ @@@@:@:@@@ @@@@@ @::@@:@@@@@@@@@@@@@#
     |                        @@@ @@@@@@ @@@@:@:@@@ @@@@@ @::@@:@@@@@@@@@@@@@#
     |                    @@@@@@@ @@@@@@ @@@@:@:@@@ @@@@@ @::@@:@@@@@@@@@@@@@#
     |                 @@@@@@ @@@ @@@@@@ @@@@:@:@@@ @@@@@ @::@@:@@@@@@@@@@@@@#
     |              ::@@@@@@@ @@@ @@@@@@ @@@@:@:@@@ @@@@@ @::@@:@@@@@@@@@@@@@#
   0 +----------------------------------------------------------------------->Gi
     0                                                                   34.76
```

New:
```
    MB
225.0^                    #
     |                 :::#
     |                 :  #
     |                 :  #
     |                 :  #
     |                 :  #
     |                 :  #
     |                 :  #     :
     |               :::  #     :
     |           :::::::  #    ::                       : :::@:::::@::::@::::@
     | :::::@::::::: :::  #:::::::::::::::::@::::::::::::::::@:::::@::::@::::@
     | : : :@::::::: :::  #::: ::::: :::::::@: ::::::::::::::@:::::@::::@::::@
     | : : :@::::::: :::  #::: ::::: :::::::@: ::::::::::::::@:::::@::::@::::@
     | : : :@::::::: :::  #::: ::::: :::::::@: ::::::::::::::@:::::@::::@::::@
     | : : :@::::::: :::  #::: ::::: :::::::@: ::::::::::::::@:::::@::::@::::@
     | : : :@::::::: :::  #::: ::::: :::::::@: ::::::::::::::@:::::@::::@::::@
     | : : :@::::::: :::  #::: ::::: :::::::@: ::::::::::::::@:::::@::::@::::@
     | : : :@::::::: :::  #::: ::::: :::::::@: ::::::::::::::@:::::@::::@::::@
     | : : :@::::::: :::  #::: ::::: :::::::@: ::::::::::::::@:::::@::::@::::@
     | : : :@::::::: :::  #::: ::::: :::::::@: ::::::::::::::@:::::@::::@::::@
   0 +----------------------------------------------------------------------->Gi
     0                                                                   15.24
```

**Comment by mflueggen** [comment] 2020-04-24 13:40
This looks much better. I still need to redo a whole TPC-H measurement and compare those results to my results from January.

The following observation might have nothing to do with this issue:
I am noticing, on a qualitative level, that the value for “stats.allocated” reported by jemalloc is slightly (let’s say 10 MB as a house number) higher than the resident set size (RES). When executing the TPCDS benchmark stats.allocated remains below RES.

**Comment by mrks** [comment] 2020-04-24 13:50
(On mobile)

I believe that reserved but not committed memory does not count towards RSS. If you allocate 1G but never touch it, jemalloc might know about it without the RSS changing.

**Comment by mflueggen** [comment] 2020-04-24 13:58
Yes. I can confirm that. On the first view jemalloc just seems to be a little more generous when executing queries for the TPC-H benchmark.

**Comment by mflueggen** [comment] 2020-04-24 14:17
> 
> 
> This looks much better. I still need to redo a whole TPC-H measurement and compare those results to my results from January.
> 
> The following observation might have nothing to do with this issue:
> I am noticing, on a qualitative level, that the value for “stats.allocated” reported by jemalloc is slightly (let’s say 10 MB as a house number) higher than the resident set size (RES). When executing the TPCDS benchmark stats.allocated remains below RES.

Please ignore this remark. I wasn't actually printing stats.allocated. I printed stats.mapped instead. stats.allocated looks fine.

Everything looks good now!

**Closed** 2020-04-28 14:46 UTC
