### ISSUE TITLE
When using GROUP BY with a column alias it groups by the wrong column

### ISSUE THREAD

**Issue by lanice** [hyrise/hyrise#578] opened 2017-12-12 12:15 UTC
In the Console:
```
load src/test/tables/aggregateoperator/groupby_int_2gb_1agg/input.tbl groupby_int_2gb_1agg
SELECT b AS whatever, SUM(c) FROM groupby_int_2gb_1agg GROUP BY whatever;
```
Gives the output:
```
=== Columns
|whatever|  SUM(c)|
|     int|    long|
=== Chunk 0 === 
|      12|      10|
|     123|      40|
|   12345|     107|
===
3 rows total (PARSE: 9 µs, COMPILE: 51 µs, EXECUTE: 641 µs (wall time))
```
I specified column `b` as the group by column (aliased to `whatever`), but the grouping is performed on column `a`. The output SHOULD look like:
```
=== Columns
|   whatever|  SUM(c)|
|   float|    long|
=== Chunk 0 === 
|   350.7|      10|
|   456.7|      44|
|   457.7|      63|
|   458.7|      40|
===
4 rows total (PARSE: 14 µs, COMPILE: 52 µs, EXECUTE: 23455 µs (wall time))
```

**Comment by lanice** [comment] 2017-12-12 12:15
For reference, the table `src/test/tables/aggregateoperator/groupby_int_2gb_1agg/input.tbl` looks like:
```
a|b|c
int|float|int
12345|456.7|20
12345|456.7|24
12345|457.7|30
12345|457.7|33
123|458.7|20
123|458.7|20
12|350.7|10
```

**Comment by mrks** [comment] 2017-12-12 13:10
Possible duplicate of #485?

**Comment by TwoLaid** [comment] 2017-12-13 09:11
Very likely to be related. But we should probably wait for @mrzzzrm to finish the column origin code, right?

**Closed** 2018-07-31 08:43 UTC
Labels: Bug
