### ISSUE TITLE
After SortMergeJoin Chunk is sorted by an invalid column ID

### ISSUE THREAD

**Issue by Alexander-Dubrawski** [hyrise/hyrise#2321] opened 2021-02-03 09:09 UTC
If we use SMJ as the default join (change the order in https://github.com/hyrise/hyrise/blob/8827a25805e866ee7cc393f1b55698ddf6ef4d23/src/lib/logical_query_plan/lqp_translator.cpp#L359) and are running the test  
`./hyriseTest --gtest_filter=SQLiteTestRunnerUnencoded/SQLiteTestRunner.CompareToSQLite/Line162WithUnencoded`  
, it failes with the following error message:

```
C++ exception with description "src/lib/operators/alias_operator.cpp:85 Chunk is sorted by an invalid column ID." thrown in the test body.
[  FAILED  ] SQLiteTestRunnerUnencoded/SQLiteTestRunner.CompareToSQLite/Line162WithUnencoded, where GetParam() = ((162, "SELECT \"left\".a1, \"left\".a2, \"right\".a1 FROM (SELECT a AS a1, a AS a2 FROM mixed) AS \"left\" JOIN (SELECT a AS a1, a AS a2 FROM mixed_null) AS \"right\" ON \"left\".a1 = \"right\".a2;"), Unencoded) (164 ms)
```

**Comment by Bouncner** [comment] 2021-02-03 11:29
The "old" code in the SMJ looks wrong. We don't adapt the right column.

Since you have fixed that glitch in #2316, could you please check if that PR fixes this issue here as well?

**Comment by Alexander-Dubrawski** [comment] 2021-02-03 14:45
> The "old" code in the SMJ looks wrong. We don't adapt the right column.
> 
> Since you have fixed that glitch in #2316, could you please check if that PR fixes this issue here as well?

But in the "old" code the right column is adapted in the same way as in the new code:

old: 

https://github.com/hyrise/hyrise/blob/master/src/lib/operators/join_sort_merge.cpp#L953-L954

new (#2316): 

https://github.com/hyrise/hyrise/blob/alexander-dubrawski/Improve_join_merge_sort_output_writing/src/lib/operators/join_sort_merge.cpp#L963-L964

The error still exists on #2316 😞 .

**Comment by Bouncner** [comment] 2021-02-04 20:47
You're right. Read that part wrong.

I took a look into the failed case.  I think the problem is with the projection operator.
In our case we have multiple columns that reference the same column (column a exists as alias `a1` and `a2`).
The projection uses a map to store the new position. And this map now overwrite the position for the first column reference. Since this map is later used for the sorting, we mark the wrong column as being sorted.

But to be honest, also the alias is quite confusing to me.

I need to have a fresh mind for that ...

**Comment by Bouncner** [comment] 2021-02-11 08:13
@mrks : probably need your help here.

There are a few issues here. First, the projection operator does assume a sorted column is not duplicated.
But it is here (`select a as a1, a as a2`).
That can be fixed relatively easy. It's probably a rare case, but the fix does not hurt.

The other issue is the alias operator. It does not alias columns 0 and 1, it acceses column IDs 0 and 0 (and 0 and 1 are sorted, 1 cannot be found: crash).
During the LQP translation, we use `input_node->get_column_id(*expression)` and **I think** that's the part where we use "merge" column IDs 0 and 1 into 0.

Any ideas about how to fix that best?

**Comment by mrks** [comment] 2021-02-11 12:46
> There are a few issues here. First, the projection operator does assume a sorted column is not duplicated.

Yepp. I think we just need to flip the order of `input_column_to_output_column`. This means that the lookup becomes a search, but that should not add any measurable costs.

> The other issue is the alias operator. It does not alias columns 0 and 1, it acceses column IDs 0 and 0 (and 0 and 1 are sorted, 1 cannot be found: crash).

I believe the issue is in the LQPTranslator:

https://github.com/hyrise/hyrise/blob/972299e72feb53b135ad3e7b645ea9e4969d22ee/src/lib/logical_query_plan/lqp_translator.cpp#L280

If we have two columns that share the same expression, we will only pass one of the column ids into the alias operator. In this place, we could easily fix this by making sure that all input expressions are used exactly once.

Maybe `get_column_id` should assert that the expression is unique? I have a feeling that we might run into similar problems in other places, too.

**Comment by Bouncner** [comment] 2021-02-24 20:32
> Maybe get_column_id should assert that the expression is unique? 
But in our case it is not unique and that's fine, right?

**Comment by mrks** [comment] 2021-02-24 20:34
Correct. The idea was that we thus force users to handle these situations. Not sure about that idea yet though.

**Comment by Bouncner** [comment] 2021-02-24 20:43
Hmm, I don't see how we could assert in `get_column_id`, since a repeated expression can happen by intention and is not necessarily a problem. Since there is no state as far as I can see, `get_column_id` cannot return "the other" expression with the next call.

We could return a list of expressions with `get_column_id`. For most operators, using `[0]` should be sufficient, for some an iteration is required. But I don't see a real value apart from this edge case here.

I don't see a good fix for the alias apart from the LQP translation and there we would _only_ fix the alias and nothing else.

**Comment by mrks** [comment] 2021-02-24 20:45
Luckily, there are only a handful users of `get_column_id`. Individually deciding how these should deal with duplicates should not be too difficult.

**Comment by Bouncner** [comment] 2021-02-24 20:55
What would you do about `find_column_id()`?

**Comment by mrks** [comment] 2021-02-25 06:46
Never mind. While we should document that those two methods only return one column id of possibly multiple results, I think I was aufzäuming the horse from the falsche Seite hier. Should we maybe just change the assertion in the Alias operator? After all, we do not really need to guarantee that both identical versions of the same column make it through the operator.

Both versions should be marked as "individually sorted by" when they come into the alias operator. If we change the for-loop to allow for multiple uses of one column id, we could fix the problem in the operator:

https://github.com/hyrise/hyrise/blob/master/src/lib/operators/alias_operator.cpp#L82-L85

What needs to change is that we do not stop after the first `std::find` result, but continue until the end of the vector. Next, drop the assertion and simply assert that the number of "individually sorted by"-columns coming in is the same same as the number going out.

**Comment by Bouncner** [comment] 2021-02-25 09:01
Not sure that I can follow. 

> Both versions should be marked as "individually sorted by" when they come into the alias operator. 
Both columns are marked in the chunk vector that stores the sorted flag, BUT the input columns IDs are [0, 0, 2]. Thus, I can't check if columnID 1 (which is supposed to be sorted) is actually the same as 0.
Changing the `std::find` doesn't fix that, or does it?

I could still count the sorted flags, yes. But I am not sure if that could lead to other errors in edge cases.

**Comment by mrks** [comment] 2021-02-25 09:59
My idea is for the Alias operator to simply ignore ColumnID 1 being sorted.

> But I am not sure if that could lead to other errors in edge cases.

I wouldn't expect it. We don't have any column lineage across operators, anyway. Once the alias operator is done, no one can distinguish the result between the two approaches.

**Closed** 2021-03-04 21:04 UTC
Labels: Bug, Test/Benchmark
