### ISSUE TITLE
Failing test BufferedLoggerTests.log_test

### ISSUE THREAD

**Issue by WojciechMula** [hyrise/hyrise#420] opened 2016-01-21 12:38 UTC
Following exception is reported: "boost::filesystem::remove: Directory not empty: "test/persistency//logs/"". The exception is raised in method BufferedLogger::truncate() at line

```
boost::filesystem::remove_all(Settings::getInstance()->getLogDir());
```

I've checked that before calling above line the directory contains some files.

Hyrise was built with the latest boost 1.6.

**Comment by Bensk1** [comment] 2016-02-25 15:57
I cannot reproduce this exception. ``boost::filesystem::remove_all`` is supposed to remove directories which are not empty. I did not find any semantic changes of this function in version 1.6 of boost.

**Comment by WojciechMula** [comment] 2016-03-07 09:53
Thanks for looking at this, probably it was related to access rights to the files. Please close the issue.

**Comment by felixeberhardt** [comment] 2017-01-12 12:56
This happens when the log directory is on a nfs share. There is still an open file handle when boost::filesystem::remove_all is called, silly renaming happens (see http://nfs.sourceforge.net/#faq_d2), directory is not empty, thus rmdir fails, thus the exception. Fix is in progress.

**Closed** 2017-01-27 12:05 UTC
