### ISSUE TITLE
hyriseMicroBenchmarks failing

### ISSUE THREAD

**Issue by benrobby** [hyrise/hyrise#2445] opened 2022-03-23 18:01 UTC
Output on latest master: 
```
➜  cmake-build-debug git:(fix-microbenchmarks) ./hyriseMicroBenchmarks 
[PERF] Hyrise is running as a debug build. at src/lib/utils/performance_warning.cpp:9
        Performance can be affected. This warning is only shown once.

Unable to determine clock rate from sysctl: hw.cpufrequency: No such file or directory
2022-03-23T18:51:10+01:00
Running ./hyriseMicroBenchmarks
Run on (8 X 24.1213 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x8)
  L1 Instruction 128 KiB (x8)
  L2 Unified 4096 KiB (x2)
Load Average: 33.96, 18.25, 11.44
***WARNING*** Library was built as DEBUG. Timings may be affected.
libc++abi: terminating with uncaught exception of type std::logic_error: src/lib/operators/abstract_operator.cpp:218 Cannot register as a consumer since operator results have already been cleared.
[1]    19442 abort      ./hyriseMicroBenchmarks
```

For me, calling `never_clear_output()` on several operators fixes it (e.g., `table_wrapper->never_clear_output()` in `src/benchmark/tpch_data_micro_benchmark.cpp` line 100). What do you think is the best solution?

**Comment by mweisgut** [comment] 2022-03-23 20:55
This looks like a duplicate of #2407.

**Comment by Bouncner** [comment] 2022-03-24 14:33
> For me, calling never_clear_output() on several operators fixes it (e.g., table_wrapper->never_clear_output() in src/benchmark/tpch_data_micro_benchmark.cpp line 100). What do you think is the best solution?

Can you please run the whole benchmark suite and check whether we run into the same problem anywhere else?

**Closed** 2022-04-25 06:16 UTC
