### ISSUE TITLE
Comparators (<, >=) ignore decimal places

### ISSUE THREAD

**Issue by janetzki** [hyrise/hyrise#1525] opened 2019-03-05 14:24 UTC
**Query**
```sql
SELECT c_custkey FROM customer WHERE c_custkey < 5.5
```

**Actual result**
```
=== Columns
|c_custkey|
|      int|
| not null|
=== Chunk 0 ===
|<ReferS> |
|        1|
|        2|
|        3|
|        4|
===
4 rows total
```

**Expected result**
```
=== Columns
|c_custkey|
|      int|
| not null|
=== Chunk 0 ===
|<ReferS> |
|        1|
|        2|
|        3|
|        4|
|        5|
===
5 rows total
```

**Other cases**
The same happens for
```sql
SELECT c_custkey FROM customer WHERE c_custkey >= 5.5 AND c_custkey <= 10
```
but not for
```sql
SELECT c_custkey FROM customer WHERE c_custkey BETWEEN 5.5 AND 10
```

**Comment by mrks** [comment] 2019-03-05 19:23
Related to / duplicate of #1306? This is probably because we cast the arguments to the type of the column being queried.

To be honest, I don't see this being tackled any time soon. From a research perspective, this is completely uninteresting, and unless it breaks any of our public or private benchmarks, there is not really a lot to gain from this. I won't keep anyone from addressing it, but I worry that it might be a bottomless pit.

**Comment by mrzzzrm** [comment] 2019-03-05 19:26
The ExpressionEvaluator would process this correct, as it doesn't perform the mentioned cast. If this is only TableScans, we could just not translate a predicate to a ColumnVsValueTableScanImpl, but instead to a ExpressionEvaluatorTableScanImpl, if Column and Value have different data types?

**Comment by mrzzzrm** [comment] 2019-03-05 19:27
(and have a good look at all our AllTypeVariant -> actual value casts.)

**Comment by mrzzzrm** [comment] 2019-03-06 07:39
>  I worry that it might be a bottomless pit.

Can you elaborate on that? Because to me fixing this seems rather straight forward.

**Comment by janetzki** [comment] 2019-03-06 07:45
@mrks You are right, it looks like a duplicate. I did not directly stumble about this behavior but originally wanted to test something semantically similar to
```sql
SELECT * FROM customer WHERE c_acctbal < (SELECT AVG(c_acctbal) FROM customer)
```
in `sql_lite_testrunner.sql` and wondered about the different result that SQLite had. So this bug can also occur without explicitly triggering it.

**Closed** 2019-04-22 08:22 UTC
Labels: Bug
