### ISSUE TITLE
Executing `plot_performance_over_time.py` throws exception

### ISSUE THREAD

**Issue by julianmenzler** [hyrise/hyrise#2258] opened 2020-11-11 22:23 UTC
```python
$ scripts/plot_performance_over_time.py bothcaches.json 

Fontconfig warning: ignoring UTF-8: not a valid region tag
Note that the reported memory consumption is also affected by the (relatively high) amount needed to store that data. For TPC-H SF 1, this is around 30 MB.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: False

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/julianmenzler/workspace_hyrise/repo_hyrise2/scripts/plot_performance_over_time.py", line 117, in <module>
    rolling = filtered_df[filtered_df["success"] is True].copy()
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: False
```

I experience the above issue on Linux & Mac systems.

**Comment by mrks** [comment] 2020-11-12 06:20
Duplicate of #2177

**Closed by mrks** 2020-11-12 06:20 UTC
Labels: Bug

**Comment by mrks** [comment] 2020-11-12 06:22
(Which is why I readily knew which line to change when it came up yesterday ;) )

**Comment by julianmenzler** [comment] 2020-11-12 08:10
> (Which is why I readily knew which line to change when it came up yesterday ;) )

Good to know. So there was no dark magic involved... ;)
