### ISSUE TITLE
TPC-H crashes with MVCC enabled; LIMIT queries are slow

### ISSUE THREAD

**Issue by toniSta** [hyrise/hyrise#1488] opened 2019-02-11 12:46 UTC
Got 2 questions about MVCC:

1) I noticed horrible query execution times when benchmarking my server. I expected `select top 1 * from lineitem;` to run in < 1ms. Indeed it takes approx. 90ms on SF 1, since the whole table gets validated (see pqp). Are there any performance issues known?
(I know I can disable MVCC for my benchmarks, but that's not a realistic scenario.)
![pqp1](https://user-images.githubusercontent.com/11941962/52563870-d8958280-2e02-11e9-8307-57ce7d03c551.png)

2) Is MVCC supposed to work in multithreaded TPC-H benchmarks? When I run it, I get a segmentation fault. (Command `./hyriseBenchmarkTPCH --scheduler --queries 1 --mvcc`)

**Comment by mrzzzrm** [comment] 2019-02-11 12:52
Ah lot could be optimized for limit. We look incredibly clumsy doing `SELECT a FROM t LIMIT 1 ORDER BY a`, too. In fact I was thinking about that yesterday. Big downside of, how do you call it?, non-pipelined query execution. Most operators would need a `size_t _limit` property and stop writing to the result table after the limit is reached. `Sort` would probably need a dedicated path.... I'd be interested in discussing options here.

**Comment by Bouncner** [comment] 2019-02-11 13:45
Would it make sense to disable concurrent scans for limit operations? As soon as there is a limit, we could do `while(!limit_reached) { sequential_chunk_scanning()`}. We would still scan the first chunk, but that would be a small overhead and we don't have to cancel concurrent jobs.

Moritz's `SELECT a FROM t LIMIT 1 ORDER BY a` looks like something that would be running "okish" in this case. The sort would still be expensive (in case we don't recognize the max/min rewriting potential), but I don't think there is a way around the expensive sort (at least for queries with LIMIT > 1). And the following filter would only parse one single chunk.

**Comment by mrks** [comment] 2019-02-11 14:30
`SELECT a FROM t LIMIT 1 ORDER BY a` is not valid SQL, assuming you mean `SELECT a FROM t ORDER BY a LIMIT 1`. How would that profit from any "concurrent scan" change? If you want the smallest value, you have to look at all of them.

We could add a `_limit` hint to the operator before the actual Limit operator. This would only work one level deep though.

Suggested read: http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.51.6635

**Comment by mrzzzrm** [comment] 2019-02-11 14:37
You really expect me to be able to write "valid SQL"? Sorry, but I write valid LQPs, and leave higher level languages to the amateurs. ;)

> If you want the smallest value, you have to look at all of them.

Perform logn lookups: yes? Sort and thereby perform nlogn lookups... Shouldn't be necessary, right? But I do not like the architectural impurity that comes from adding a `_limit` property to joins, scans, validates and sorts...

**Comment by mrks** [comment] 2019-02-11 14:41
Maybe the first question should be: What problem are we trying to solve?

**Comment by mrks** [comment] 2019-02-11 14:48
Also, if we really care(d) about `SELECT a FROM t ORDER BY a LIMIT 1`, I would rather rewrite the LQP into `SELECT MIN(a) FROM t`. Still, this wouldn't solve the validate issue, where all rows get validated. That happens because validate does not know how many rows are needed later.

**Comment by Bouncner** [comment] 2019-02-11 14:53
I just realized that I was thinking about something else. Ignore my stupid words.

**Comment by mrks** [comment] 2019-02-11 15:10
Regarding the second issue: I am pretty sure that the issue lies in `std::vector<std::shared_ptr<AbstractTask>> BenchmarkRunner::_schedule_query`. The transaction context should be held by the pipeline. Extracting the tasks from a pipeline, throwing away the pipeline, and executing the pipeline later is not a valid execution model.

**Comment by mrzzzrm** [comment] 2019-03-20 07:52
There are two questions in this issue, which makes it a bit hard to handle it. I think we can get the first one out of the way. To execute LIMIT queries faster in the general case we'd probably need to switch to a pipelined architecture which won't happen soon, I guess.

The second question, @toniSta, is interesting because I can't reproduce the crash anymore. `./hyriseBenchmarkTPCH --scheduler --queries 1 --mvcc -t 300 --clients 10` ran fine on pella in a release build, for the specified 5 minutes, without any crashes. 
Locally I am not having any troubles with a debug build either.

Closing for now, but feel free to reopen if we can get a repro on this.

**Closed by mrzzzrm** 2019-03-20 07:52 UTC
Labels: Bug, Performance

**Comment by toniSta** [comment] 2019-03-20 11:50
Can't reproduce this crash either. Seems to be fixed right now. Issue can stay closed.
