### ISSUE TITLE
Benchmarks fail with Cuckoo hash error

### ISSUE THREAD

**Issue by lanice** [hyrise/hyrise#924] opened 2018-06-21 08:02 UTC
The benchmarks (running on Athen for the Speedcenter) fail somewhat randomly (but a lot) with the following error, during the JoinHash Benchmarks:

`src/lib/utils/cuckoo_hashtable.hpp:93 There is a cycle in Cuckoo. Need to rehash with different hash functions`

If that's helpful, here the parameters for the benchmarks we're running:
```
/var/www/codespeed/repo/build-release/hyriseOperatorBenchmark
--benchmark_format=console
--benchmark_out=/var/www/codespeed/repo/last_benchmark.json
--benchmark_out_format=json
--benchmark_repetitions=5
--benchmark_report_aggregates_only=true
```

**Comment by mrzzzrm** [comment] 2018-06-21 08:09
https://github.com/hyrise/hyrise/pull/785 for a quick fix

**Comment by mrzzzrm** [comment] 2018-06-21 08:10
So this is likely a duplicate of #798

**Closed by mrzzzrm** 2018-06-21 08:10 UTC
Labels: Bug, Test/Benchmark

**Comment by lanice** [comment] 2018-06-21 08:22
Thanks! Doesn't solve the problem for the Speedcenter unfortunately, since it takes the repository as it is for the specific commit it benchmarks.
So either I guess I'll let the speedcenter script repeat the benchmarks until the error does not show, or for each commit I'll let the script modify the code as you suggested, which sounds way too wacky
